item1 = input("Digite o item 1: ")
item2 = input("Digite o item 2: ")
item3 = input("Digite o item 3: ")
item4 = input("Digite o item 4: ")
item5 = input("Digite o item 5: ")

qtde1 = input("Digite a quantidade do item 1: ")
qtde2 = input("Digite a quantidade do item 2: ")
qtde3 = input("Digite a quantidade do item 3: ")
qtde4 = input("Digite a quantidade do item 4: ")
qtde5 = input("Digite a quantidade do item 5: ")

print(f"A quantidade do {item1} é {qtde1}")
print(f"A quantidade do {item2} é {qtde2}")
print(f"A quantidade do {item3} é {qtde3}")
print(f"A quantidade do {item4} é {qtde4}")
print(f"A quantidade do {item5} é {qtde5}")